#!/bin/bash
set -e
set -x

readonly USERHOME="/home/$(whoami)"
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"

# Install theme
mkdir "$USERHOME/.themes" -p
cd "$USERHOME/.themes/" || exit

[[ ! -d vimix-gtk-themes ]] && git clone https://github.com/vinceliuice/vimix-gtk-themes.git
bash vimix-gtk-themes/Install

sed -i 's/<property name="theme" type="string" value=".*"\/>/<property name="theme" type="string" value="vimix-light-doder"\/>/g' ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml
xfconf-query -c xfwm4 -p /general/theme -s "vimix-light-doder"

# Install icons & cursor
mkdir "$USERHOME/.icons" -p
cd "$USERHOME/.icons/" || exit

wget https://github.com/vinceliuice/vimix-icon-theme/archive/master.zip
unzip master.zip
bash vimix-icon-theme-master/install.sh
xfconf-query -c xsettings -p /Net/IconThemeName -s "Vimix-Paper"

# Install wallpaper
akicd "$USERHOME/Pictures/" || exit
wget https://raw.githubusercontent.com/cristianarbe/gettrisquel.org/master/images/banner.jpg
xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace0/last-image -s "$USERHOME/Pictures/banner.jpg"

# Install panel setup
pkill xfconfd
[[ -f "$USERHOME/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml" ]] && rm "$USERHOME/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml"

cd "/tmp/gnad/modules" || exit
cp "modules/xfce4-panel.xml" "$USERHOME/.config/xfce4/xfconf/xfce-perchannel-xml/"
# Fix pulseaudio icon
cp "modules/gtk.css" "$USERHOME/.config/gtk-3.0/"
# Install xfwm4
[[ -f "$USERHOME/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml" ]] && rm "$USERHOME/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml"
cp "modules/xfwm4.xml" "$USERHOME/.config/xfce4/xfconf/xfce-perchannel-xml"
[[ -f "$USERHOME/.config/xfce4/panel/whiskermenu-1.rc" ]] && rm "$USERHOME/.config/xfce4/panel/whiskermenu-1.rc"
cp "modules/whiskermenu-1.rc" "$USERHOME/.config/xfce4/panel/"
xfconf-query -c xsettings -p /Gtk/CursorThemeName -s Breeze

# Install font
mkdir -p "$USERHOME/.fonts/"
cd "$USERHOME/.fonts/" || exit
wget -q https://www.fontsquirrel.com/fonts/download/clear-sans
unzip -o clear-sans
xfconf-query -c xsettings -p /Gtk/FontName -s "Clear Sans 12"
xfconf-query -c xfwm4 -p /general/title_font -s "Clear Sans 12"

# Install keyboard shortcuts
rm "$USERHOME/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"
cp "modules/xfce4-keyboard-shortcuts.xml" "$USERHOME/.config/xfce4/xfconf/xfce-perchannel-xml"

xfce4-panel -r
/usr/lib64/xfce4/xfconf/xfconfd &> /dev/null &

read -pr "Changes will not be applied until you log out and log back in. You are going to be logged out now. Save your work and press enter to continue..."

xfce4-session-logout