#!/usr/bin/env bash
#
# Executable file of GNad
# TODO(cristianarbe): Always check return values and give informative return values.

readonly CONFIG_FILE="$1"
readonly CONFIG_FILE_PATH="${CONFIG_FILE%/*}"

set -e

# Load all modules
for file in modules/*.sh; do
    # shellcheck disable=SC1090
    source "$file"
done

case $1 in
"-h" | "--help")
    cat modules/help.txt
    ;;
"--version")
    cat modules/version.txt
    ;;
"install")
    [[ $EUID -ne 0 ]] && echo "This program must be run as root" && exit 1
    # shellcheck disable=SC1090
    if [[ -z "$2" ]]; then
        source "$2"

        [[ ! -d logs ]] && mkdir logs

        echo 'Installing packages...'
        install_apt_packages >>logs/gnad.log
        echo 'Installing extra packages...'
        install_extra_packages >>logs/gnad.log
        echo 'Installing themes...'
        setup_appearance >>logs/gnad.log
        echo 'Install completed.'
    else
        echo "gnad: missing file. See 'gnad --help' for more info."
    fi
    ;;
"get")
    if [[ -z "$2" ]]; then
        err ":)"
    else
        echo "gnad: missing file. See 'gnad --help' for more info."
    fi
    ;;
*)
    echo "gnad: '$1': invalid option. See 'gnad --help' for more info."
    ;;
esac
